//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizza_Application.DataLayer.EntityFramwork
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int orderId { get; set; }
        public string name { get; set; }
        public string phoneNumber { get; set; }
        public string dateTime { get; set; }
        public int numOfPizzas { get; set; }
    }
}
