using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Pizza_Application.Models
{
    /// <summary>
    /// sets up the order class
    /// </summary>
    public class Order
    {
        /// <summary>
        /// sets up the unique id generated by the db
        /// </summary>
        public int orderId { get; set; }
        /// <summary>
        /// the name entered by the user
        /// </summary>
        public string name { get; set; }
        /// <summary>
        /// phone number entered by the user
        /// </summary>
        public string phoneNumber { get; set; }
        /// <summary>
        /// phone number entered by the user
        /// </summary>
        public string dateTime { get; set; }
        /// <summary>
        /// the number of pizzas the user would like to order
        /// </summary>
        public int numOfPizzas { get; set; }
    }
}