using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Pizza_Application.Models
{
    /// <summary>
    /// sets up the order class
    /// </summary>
    public class OrderViewModel
    {
        /// <summary>
        /// sets up the unique id generated by the db
        /// </summary>
        public int OrderId { get; set; }
        /// <summary>
        /// the name entered by the user
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// phone number entered by the user
        /// </summary>
        public string PhoneNumber { get; set; }
        /// <summary>
        /// phone number entered by the user
        /// </summary>
        public string DateTime { get; set; }
        /// <summary>
        /// the number of pizzas the user would like to order
        /// </summary>
        public int NumOfPizzas { get; set; }
    }
}